live_config_reload = true

[window]
startup_mode = "Maximized"
dynamic_padding = true
decorations_theme_variant = "dark"
padding = { x = 0, y = 3 }

[font]
size = 12
normal = { family = "Monaco", style = "Regular"}
